apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse-main
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    jsonData:
      defaultDatabase: stream_analytics
      host: clickhouse
      port: "8123"
      protocol: http
      secure: "false"
      username: default
      dialTimeout: "10"
      queryTimeout: "60"
    secureJsonData:
      password: clickhouse
    editable: true
